service/cities_weather/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('djadmin/', admin.site.urls),
    path('',include('core.urls',namespace='main'))
]

service/core/urls.py
from django.urls import path
from .views import (home_page, temp_city_page, cities_distance,
                    city_list_temp, city_list_dist_1, city_list_dist_2)


app_name = 'core'

urlpatterns = [
    path('',home_page,name='home'),
    path('temperature/<slug:city_slug>',temp_city_page,name='temp_city'),
    path('distance', cities_distance, name='distance')
]

htmx_urlpatterns = [
    path('cities-temp',city_list_temp,name='cities_temp'),
    path('cities-dist-1',city_list_dist_1,name='cities_dist_1'),
    path('cities-dist-2',city_list_dist_2,name='cities_dist_2'),
]

urlpatterns += htmx_urlpatterns

service/core/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.utils.translation import gettext as _
from django.core.cache import cache

from .utils import get_city_data, get_dist, get_weather_icon

import json
from datetime import datetime, timedelta, timezone
import pytz
from cities_light.models import City


def home_page(request):
    return render(request,'core/home.html')


def get_current_datetime(offset_seconds: int):
    tz = timezone(timedelta(seconds=offset_seconds))
    now = datetime.now(tz)

    current_time = now.time()
    current_date = now.date()

    return {'current_time':current_time,'current_date':current_date}


def temp_city_page(request, city_slug):
    city = get_object_or_404(City,slug=city_slug)

    weather_data = get_city_data.delay(city.name_ascii).get()
    weather_data = json.loads(weather_data)
    temperature = round(weather_data['main']['temp'])
    status = weather_data['weather'][0]['main']
    more_status = weather_data['weather'][0]['description']

    icon_tag = weather_data['weather'][0]['icon']
    weather_icon_url = get_weather_icon(icon_tag)

    offset_seconds = int(weather_data['timezone'])

    current_datetime = get_current_datetime(offset_seconds)

    current_time = current_datetime['current_time']
    current_date = current_datetime['current_date']
    

    context = {
        'city':city,
        'temp':temperature,
        'status':status, # Если хочется добавить картинки уже из статики (не используется в HTML шаблоне)
        'more_status':_(more_status),
        'icon_url':weather_icon_url,
        'current_time':current_time,
        'current_date':current_date,
    }

    return render(request,'core/city_page.html',context=context)


def cities_distance(request):
    name_city_from = request.GET.get('from',None)
    name_city_to = request.GET.get('to',None)

    if name_city_from is None or name_city_to is None:
        return HttpResponse('Выберите оба города')

    cache_distance = cache.get(f"{name_city_from}-{name_city_to}")
    cache_distance_reverse = cache.get(f"{name_city_to}-{name_city_from}")

    city_from = get_object_or_404(City,alternate_names=name_city_from)
    city_to = get_object_or_404(City,alternate_names=name_city_to)

    if city_from == city_to:
        distance = 0
    else:
        distance = cache_distance or cache_distance_reverse
        if not bool(distance):

            data_from = get_city_data.delay(city_from.name_ascii).get()
            data_to = get_city_data.delay(city_to.name_ascii).get()
            data_from = json.loads(data_from)
            data_to = json.loads(data_to)

            lon_from = data_from['coord']['lon']
            lat_from = data_from['coord']['lat']
            lon_to = data_to['coord']['lon']
            lat_to = data_to['coord']['lat']

            distance = get_dist(lon_from,lat_from,lon_to,lat_to)

            cache.set(f"{name_city_from}-{name_city_to}",distance,20)

    context = {
        'city_from':city_from,
        'city_to':city_to,
        'distance':distance,
    }
    return render(request,'core/distance_page.html',context=context)


# HTMX minor function
def get_cities(request,city_title):
    city = request.GET.get(city_title,'')
    if city == '':
        cities = []
    else:
        cities = City.objects.filter(alternate_names__icontains=city)
    return cities


# HTMX view
def city_list_temp(request):
    cities = get_cities(request,'city')
    return render(request,'core/includes/cities_temp.html',context={'cities':cities})


# HTMX view
def city_list_dist_1(request):
    cities = get_cities(request,'from')
    return render(request,'core/includes/cities_dist_1.html',context={'cities':cities})


# HTMX view
def city_list_dist_2(request):
    cities = get_cities(request,'to')
    return render(request,'core/includes/cities_dist_2.html',context={'cities':cities})

service/core/templates/core/city_page.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}Погода | {{city.alternate_names}}{% endblock title %}

{% block header %}
{% include "core/includes/to_home_header.html" %}
{% endblock header %}

{% block content %}
<div class="city-card__container">
    <div class="city-card__info">
        <h1>{{city.alternate_names}}</h1>
        <img src={{icon_url}} alt="{{more_status}}">
        <div class="city-card__status">
            <h2>{{temp}} &deg;C</h2>
            <p>{{more_status}}</p>
        </div>
    </div>
    <div class="city-card__date-time">
        <p>{{current_date}}</p>
        <p>{{current_time}}</p>
    </div>
    
</div>
{% endblock content %}

service/core/templates/core/distance_page.html
{% extends "base.html" %}

{% block title %}{{city_from.alternate_names}} | {{city_to.alternate_names}}{% endblock title %}

{% block header %}
{% include "core/includes/to_home_header.html" %}
{% endblock header %}

{% block content %}
<div class="distance-card__container">
    <div class="distance-card__text-wrapper">
        <p>Расстояние</p>
        <h1>
            <a href="{% url "main:temp_city" city_from.slug%}">{{city_from.alternate_names}}</a>
             - 
            <a href="{% url "main:temp_city" city_to.slug%}">{{city_to.alternate_names}}</a>
            <br>{{distance}} км
        </h1>
    </div>
</div>
{% endblock content %}

service/core/templates/core/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}Главная{% endblock title %}

{% block header %}
<nav>
    <h1>Погода | Расстояние</h1>
</nav>
{% endblock header %}

{% block content %}
    
    <!-- Погода -->
    <div class="weather-form__box home-form-box">
        <h1 class="form__title">Узнать погоду</h1>
        <div class="form__center-box">
            <input name="city" type="text" placeholder="Выберите город" class="form__input"
            hx-trigger="keyup" hx-get="{% url "main:cities_temp" %}" hx-target=".weather-form__box #cities-list">
            {% include "core/includes/cities_temp.html" %}
        </div>
    </div>

    <!-- Расстояние -->
    <div class="distance-form__box home-form-box">
        <h1 class="form__title form__title__yellow-shadow">Определить расстояние между</h1>
        <div class="form__center-box distance-form__center-box">
            <form action="{% url "main:distance" %}" method="get">
                    <div class="distance-form__left-wrapper">
                        <input name="from" type="text" placeholder="Выберите город" class="form__input" id="from-city-slug"
                        hx-trigger="keyup" hx-get="{% url "main:cities_dist_1" %}" hx-target=".distance-form__left-wrapper #cities-list"
                        >
                        {% include "core/includes/cities_dist_1.html" %}
                    </div>
                    <h1 class="form__title form__title__yellow-shadow">и</h1>
                    <div class="distance-form__right-wrapper">
                        <input name="to" type="text" placeholder="Выберите город" class="form__input" id="to-city-slug"
                        hx-trigger="keyup" hx-get="{% url "main:cities_dist_2" %}" hx-target=".distance-form__right-wrapper #cities-list"
                        >
                        {% include "core/includes/cities_dist_2.html" %}
                    </div>
                <button onclick="checkMinCities(event)" class="distance-form__btn" type="submit">Посчитать</button>
            </form>
        </div>   
    </div>
{% endblock content %}

service/core/templates/core/includes/cities_dist_1.html
<div id="cities-list" class="cities-list">
    {% for city in cities %}
        <p onclick="setCityValue(this,'left')">{{city.alternate_names}}</p>
    {% endfor %}
</div>

service/core/templates/core/includes/cities_dist_2.html
<div id="cities-list" class="cities-list">
    {% for city in cities %}
        <p onclick="setCityValue(this,'right')">{{city.alternate_names}}</p>
    {% endfor %}
</div>

service/core/templates/core/includes/cities_temp.html
<div id="cities-list" class="cities-list">
    {% for city in cities %}
        <a href="{% url "main:temp_city" city.slug %}">{{city.alternate_names}}</a>
    {% endfor %}
</div>

service/core/templates/core/includes/to_home_header.html
<nav>
    <a href="{% url "main:home" %}">На главную</a>
</nav>

service/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <!--Общие стили-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!--Стили для информации о городе-->
    <link rel="stylesheet" href="{% static 'css/city_page.css' %}">
    <!--Стили для расстояния-->
    <link rel="stylesheet" href="{% static 'css/distance.css' %}">
    <!-- HTMX --> 
    <script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.6/dist/htmx.min.js" integrity="sha384-Akqfrbj/HpNVo8k11SXBb6TlBWmXXlYQrCSqEWmyKJe+hDm3Z/B2WVG4smwBkRVm" crossorigin="anonymous"></script>
</head>
<body>
    {% block header %}{% endblock header %}
    <div class="main-container">
        {% block content %}{% endblock content %}
    </div>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/for_cities_dist.js' %}"></script>
</body>
</html>